/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AreaRouteImport } from './routes/_area'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClienteLoginRouteImport } from './routes/cliente.login'
import { Route as AppPesquisaRouteImport } from './routes/_app/pesquisa'
import { Route as AppMapaRouteImport } from './routes/_app/mapa'
import { Route as AppFinanceiroRouteImport } from './routes/_app/financeiro'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppConfiguracoesRouteImport } from './routes/_app/configuracoes'
import { Route as AppClientesRouteImport } from './routes/_app/clientes'
import { Route as AppCarnesRouteImport } from './routes/_app/carnes'
import { Route as AreaClienteIndexRouteImport } from './routes/_area.cliente.index'
import { Route as AreaClienteWifiRouteImport } from './routes/_area.cliente.wifi'
import { Route as AreaClienteFinanceiroRouteImport } from './routes/_area.cliente.financeiro'
import { Route as AreaClienteConexaoRouteImport } from './routes/_area.cliente.conexao'
import { Route as AreaClienteAvisosRouteImport } from './routes/_area.cliente.avisos'
import { Route as AreaClienteAtendimentoRouteImport } from './routes/_area.cliente.atendimento'
import { Route as AppClientesIdRouteImport } from './routes/_app/clientes.$id'
import { Route as ApiPublicMikrotikSyncRouteImport } from './routes/api/public/mikrotik/sync'
import { Route as ApiPublicMikrotikStatusRouteImport } from './routes/api/public/mikrotik/status'
import { Route as ApiPublicClienteNotificacoesRouteImport } from './routes/api/public/cliente/notificacoes'
import { Route as ApiPublicClienteMeRouteImport } from './routes/api/public/cliente/me'
import { Route as ApiPublicClienteFinanceiroRouteImport } from './routes/api/public/cliente/financeiro'
import { Route as ApiPublicClienteAvisosRouteImport } from './routes/api/public/cliente/avisos'
import { Route as ApiPublicClienteAuthLoginRouteImport } from './routes/api/public/cliente/auth/login'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AreaRoute = AreaRouteImport.update({
  id: '/_area',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteLoginRoute = ClienteLoginRouteImport.update({
  id: '/cliente/login',
  path: '/cliente/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPesquisaRoute = AppPesquisaRouteImport.update({
  id: '/pesquisa',
  path: '/pesquisa',
  getParentRoute: () => AppRoute,
} as any)
const AppMapaRoute = AppMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppCarnesRoute = AppCarnesRouteImport.update({
  id: '/carnes',
  path: '/carnes',
  getParentRoute: () => AppRoute,
} as any)
const AreaClienteIndexRoute = AreaClienteIndexRouteImport.update({
  id: '/cliente/',
  path: '/cliente/',
  getParentRoute: () => AreaRoute,
} as any)
const AreaClienteWifiRoute = AreaClienteWifiRouteImport.update({
  id: '/cliente/wifi',
  path: '/cliente/wifi',
  getParentRoute: () => AreaRoute,
} as any)
const AreaClienteFinanceiroRoute = AreaClienteFinanceiroRouteImport.update({
  id: '/cliente/financeiro',
  path: '/cliente/financeiro',
  getParentRoute: () => AreaRoute,
} as any)
const AreaClienteConexaoRoute = AreaClienteConexaoRouteImport.update({
  id: '/cliente/conexao',
  path: '/cliente/conexao',
  getParentRoute: () => AreaRoute,
} as any)
const AreaClienteAvisosRoute = AreaClienteAvisosRouteImport.update({
  id: '/cliente/avisos',
  path: '/cliente/avisos',
  getParentRoute: () => AreaRoute,
} as any)
const AreaClienteAtendimentoRoute = AreaClienteAtendimentoRouteImport.update({
  id: '/cliente/atendimento',
  path: '/cliente/atendimento',
  getParentRoute: () => AreaRoute,
} as any)
const AppClientesIdRoute = AppClientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppClientesRoute,
} as any)
const ApiPublicMikrotikSyncRoute = ApiPublicMikrotikSyncRouteImport.update({
  id: '/api/public/mikrotik/sync',
  path: '/api/public/mikrotik/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMikrotikStatusRoute = ApiPublicMikrotikStatusRouteImport.update({
  id: '/api/public/mikrotik/status',
  path: '/api/public/mikrotik/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicClienteNotificacoesRoute =
  ApiPublicClienteNotificacoesRouteImport.update({
    id: '/api/public/cliente/notificacoes',
    path: '/api/public/cliente/notificacoes',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicClienteMeRoute = ApiPublicClienteMeRouteImport.update({
  id: '/api/public/cliente/me',
  path: '/api/public/cliente/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicClienteFinanceiroRoute =
  ApiPublicClienteFinanceiroRouteImport.update({
    id: '/api/public/cliente/financeiro',
    path: '/api/public/cliente/financeiro',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicClienteAvisosRoute = ApiPublicClienteAvisosRouteImport.update({
  id: '/api/public/cliente/avisos',
  path: '/api/public/cliente/avisos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicClienteAuthLoginRoute =
  ApiPublicClienteAuthLoginRouteImport.update({
    id: '/api/public/cliente/auth/login',
    path: '/api/public/cliente/auth/login',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/carnes': typeof AppCarnesRoute
  '/clientes': typeof AppClientesRouteWithChildren
  '/configuracoes': typeof AppConfiguracoesRoute
  '/dashboard': typeof AppDashboardRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/mapa': typeof AppMapaRoute
  '/pesquisa': typeof AppPesquisaRoute
  '/cliente/login': typeof ClienteLoginRoute
  '/clientes/$id': typeof AppClientesIdRoute
  '/cliente/atendimento': typeof AreaClienteAtendimentoRoute
  '/cliente/avisos': typeof AreaClienteAvisosRoute
  '/cliente/conexao': typeof AreaClienteConexaoRoute
  '/cliente/financeiro': typeof AreaClienteFinanceiroRoute
  '/cliente/wifi': typeof AreaClienteWifiRoute
  '/cliente/': typeof AreaClienteIndexRoute
  '/api/public/cliente/avisos': typeof ApiPublicClienteAvisosRoute
  '/api/public/cliente/financeiro': typeof ApiPublicClienteFinanceiroRoute
  '/api/public/cliente/me': typeof ApiPublicClienteMeRoute
  '/api/public/cliente/notificacoes': typeof ApiPublicClienteNotificacoesRoute
  '/api/public/mikrotik/status': typeof ApiPublicMikrotikStatusRoute
  '/api/public/mikrotik/sync': typeof ApiPublicMikrotikSyncRoute
  '/api/public/cliente/auth/login': typeof ApiPublicClienteAuthLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/carnes': typeof AppCarnesRoute
  '/clientes': typeof AppClientesRouteWithChildren
  '/configuracoes': typeof AppConfiguracoesRoute
  '/dashboard': typeof AppDashboardRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/mapa': typeof AppMapaRoute
  '/pesquisa': typeof AppPesquisaRoute
  '/cliente/login': typeof ClienteLoginRoute
  '/clientes/$id': typeof AppClientesIdRoute
  '/cliente/atendimento': typeof AreaClienteAtendimentoRoute
  '/cliente/avisos': typeof AreaClienteAvisosRoute
  '/cliente/conexao': typeof AreaClienteConexaoRoute
  '/cliente/financeiro': typeof AreaClienteFinanceiroRoute
  '/cliente/wifi': typeof AreaClienteWifiRoute
  '/cliente': typeof AreaClienteIndexRoute
  '/api/public/cliente/avisos': typeof ApiPublicClienteAvisosRoute
  '/api/public/cliente/financeiro': typeof ApiPublicClienteFinanceiroRoute
  '/api/public/cliente/me': typeof ApiPublicClienteMeRoute
  '/api/public/cliente/notificacoes': typeof ApiPublicClienteNotificacoesRoute
  '/api/public/mikrotik/status': typeof ApiPublicMikrotikStatusRoute
  '/api/public/mikrotik/sync': typeof ApiPublicMikrotikSyncRoute
  '/api/public/cliente/auth/login': typeof ApiPublicClienteAuthLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_area': typeof AreaRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/carnes': typeof AppCarnesRoute
  '/_app/clientes': typeof AppClientesRouteWithChildren
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/financeiro': typeof AppFinanceiroRoute
  '/_app/mapa': typeof AppMapaRoute
  '/_app/pesquisa': typeof AppPesquisaRoute
  '/cliente/login': typeof ClienteLoginRoute
  '/_app/clientes/$id': typeof AppClientesIdRoute
  '/_area/cliente/atendimento': typeof AreaClienteAtendimentoRoute
  '/_area/cliente/avisos': typeof AreaClienteAvisosRoute
  '/_area/cliente/conexao': typeof AreaClienteConexaoRoute
  '/_area/cliente/financeiro': typeof AreaClienteFinanceiroRoute
  '/_area/cliente/wifi': typeof AreaClienteWifiRoute
  '/_area/cliente/': typeof AreaClienteIndexRoute
  '/api/public/cliente/avisos': typeof ApiPublicClienteAvisosRoute
  '/api/public/cliente/financeiro': typeof ApiPublicClienteFinanceiroRoute
  '/api/public/cliente/me': typeof ApiPublicClienteMeRoute
  '/api/public/cliente/notificacoes': typeof ApiPublicClienteNotificacoesRoute
  '/api/public/mikrotik/status': typeof ApiPublicMikrotikStatusRoute
  '/api/public/mikrotik/sync': typeof ApiPublicMikrotikSyncRoute
  '/api/public/cliente/auth/login': typeof ApiPublicClienteAuthLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/carnes'
    | '/clientes'
    | '/configuracoes'
    | '/dashboard'
    | '/financeiro'
    | '/mapa'
    | '/pesquisa'
    | '/cliente/login'
    | '/clientes/$id'
    | '/cliente/atendimento'
    | '/cliente/avisos'
    | '/cliente/conexao'
    | '/cliente/financeiro'
    | '/cliente/wifi'
    | '/cliente/'
    | '/api/public/cliente/avisos'
    | '/api/public/cliente/financeiro'
    | '/api/public/cliente/me'
    | '/api/public/cliente/notificacoes'
    | '/api/public/mikrotik/status'
    | '/api/public/mikrotik/sync'
    | '/api/public/cliente/auth/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/carnes'
    | '/clientes'
    | '/configuracoes'
    | '/dashboard'
    | '/financeiro'
    | '/mapa'
    | '/pesquisa'
    | '/cliente/login'
    | '/clientes/$id'
    | '/cliente/atendimento'
    | '/cliente/avisos'
    | '/cliente/conexao'
    | '/cliente/financeiro'
    | '/cliente/wifi'
    | '/cliente'
    | '/api/public/cliente/avisos'
    | '/api/public/cliente/financeiro'
    | '/api/public/cliente/me'
    | '/api/public/cliente/notificacoes'
    | '/api/public/mikrotik/status'
    | '/api/public/mikrotik/sync'
    | '/api/public/cliente/auth/login'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_area'
    | '/auth'
    | '/_app/carnes'
    | '/_app/clientes'
    | '/_app/configuracoes'
    | '/_app/dashboard'
    | '/_app/financeiro'
    | '/_app/mapa'
    | '/_app/pesquisa'
    | '/cliente/login'
    | '/_app/clientes/$id'
    | '/_area/cliente/atendimento'
    | '/_area/cliente/avisos'
    | '/_area/cliente/conexao'
    | '/_area/cliente/financeiro'
    | '/_area/cliente/wifi'
    | '/_area/cliente/'
    | '/api/public/cliente/avisos'
    | '/api/public/cliente/financeiro'
    | '/api/public/cliente/me'
    | '/api/public/cliente/notificacoes'
    | '/api/public/mikrotik/status'
    | '/api/public/mikrotik/sync'
    | '/api/public/cliente/auth/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AreaRoute: typeof AreaRouteWithChildren
  AuthRoute: typeof AuthRoute
  ClienteLoginRoute: typeof ClienteLoginRoute
  ApiPublicClienteAvisosRoute: typeof ApiPublicClienteAvisosRoute
  ApiPublicClienteFinanceiroRoute: typeof ApiPublicClienteFinanceiroRoute
  ApiPublicClienteMeRoute: typeof ApiPublicClienteMeRoute
  ApiPublicClienteNotificacoesRoute: typeof ApiPublicClienteNotificacoesRoute
  ApiPublicMikrotikStatusRoute: typeof ApiPublicMikrotikStatusRoute
  ApiPublicMikrotikSyncRoute: typeof ApiPublicMikrotikSyncRoute
  ApiPublicClienteAuthLoginRoute: typeof ApiPublicClienteAuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_area': {
      id: '/_area'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AreaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente/login': {
      id: '/cliente/login'
      path: '/cliente/login'
      fullPath: '/cliente/login'
      preLoaderRoute: typeof ClienteLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/pesquisa': {
      id: '/_app/pesquisa'
      path: '/pesquisa'
      fullPath: '/pesquisa'
      preLoaderRoute: typeof AppPesquisaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mapa': {
      id: '/_app/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof AppMapaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financeiro': {
      id: '/_app/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes': {
      id: '/_app/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/carnes': {
      id: '/_app/carnes'
      path: '/carnes'
      fullPath: '/carnes'
      preLoaderRoute: typeof AppCarnesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_area/cliente/': {
      id: '/_area/cliente/'
      path: '/cliente'
      fullPath: '/cliente/'
      preLoaderRoute: typeof AreaClienteIndexRouteImport
      parentRoute: typeof AreaRoute
    }
    '/_area/cliente/wifi': {
      id: '/_area/cliente/wifi'
      path: '/cliente/wifi'
      fullPath: '/cliente/wifi'
      preLoaderRoute: typeof AreaClienteWifiRouteImport
      parentRoute: typeof AreaRoute
    }
    '/_area/cliente/financeiro': {
      id: '/_area/cliente/financeiro'
      path: '/cliente/financeiro'
      fullPath: '/cliente/financeiro'
      preLoaderRoute: typeof AreaClienteFinanceiroRouteImport
      parentRoute: typeof AreaRoute
    }
    '/_area/cliente/conexao': {
      id: '/_area/cliente/conexao'
      path: '/cliente/conexao'
      fullPath: '/cliente/conexao'
      preLoaderRoute: typeof AreaClienteConexaoRouteImport
      parentRoute: typeof AreaRoute
    }
    '/_area/cliente/avisos': {
      id: '/_area/cliente/avisos'
      path: '/cliente/avisos'
      fullPath: '/cliente/avisos'
      preLoaderRoute: typeof AreaClienteAvisosRouteImport
      parentRoute: typeof AreaRoute
    }
    '/_area/cliente/atendimento': {
      id: '/_area/cliente/atendimento'
      path: '/cliente/atendimento'
      fullPath: '/cliente/atendimento'
      preLoaderRoute: typeof AreaClienteAtendimentoRouteImport
      parentRoute: typeof AreaRoute
    }
    '/_app/clientes/$id': {
      id: '/_app/clientes/$id'
      path: '/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof AppClientesIdRouteImport
      parentRoute: typeof AppClientesRoute
    }
    '/api/public/mikrotik/sync': {
      id: '/api/public/mikrotik/sync'
      path: '/api/public/mikrotik/sync'
      fullPath: '/api/public/mikrotik/sync'
      preLoaderRoute: typeof ApiPublicMikrotikSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mikrotik/status': {
      id: '/api/public/mikrotik/status'
      path: '/api/public/mikrotik/status'
      fullPath: '/api/public/mikrotik/status'
      preLoaderRoute: typeof ApiPublicMikrotikStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cliente/notificacoes': {
      id: '/api/public/cliente/notificacoes'
      path: '/api/public/cliente/notificacoes'
      fullPath: '/api/public/cliente/notificacoes'
      preLoaderRoute: typeof ApiPublicClienteNotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cliente/me': {
      id: '/api/public/cliente/me'
      path: '/api/public/cliente/me'
      fullPath: '/api/public/cliente/me'
      preLoaderRoute: typeof ApiPublicClienteMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cliente/financeiro': {
      id: '/api/public/cliente/financeiro'
      path: '/api/public/cliente/financeiro'
      fullPath: '/api/public/cliente/financeiro'
      preLoaderRoute: typeof ApiPublicClienteFinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cliente/avisos': {
      id: '/api/public/cliente/avisos'
      path: '/api/public/cliente/avisos'
      fullPath: '/api/public/cliente/avisos'
      preLoaderRoute: typeof ApiPublicClienteAvisosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cliente/auth/login': {
      id: '/api/public/cliente/auth/login'
      path: '/api/public/cliente/auth/login'
      fullPath: '/api/public/cliente/auth/login'
      preLoaderRoute: typeof ApiPublicClienteAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppClientesRouteChildren {
  AppClientesIdRoute: typeof AppClientesIdRoute
}

const AppClientesRouteChildren: AppClientesRouteChildren = {
  AppClientesIdRoute: AppClientesIdRoute,
}

const AppClientesRouteWithChildren = AppClientesRoute._addFileChildren(
  AppClientesRouteChildren,
)

interface AppRouteChildren {
  AppCarnesRoute: typeof AppCarnesRoute
  AppClientesRoute: typeof AppClientesRouteWithChildren
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppMapaRoute: typeof AppMapaRoute
  AppPesquisaRoute: typeof AppPesquisaRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCarnesRoute: AppCarnesRoute,
  AppClientesRoute: AppClientesRouteWithChildren,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppMapaRoute: AppMapaRoute,
  AppPesquisaRoute: AppPesquisaRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AreaRouteChildren {
  AreaClienteAtendimentoRoute: typeof AreaClienteAtendimentoRoute
  AreaClienteAvisosRoute: typeof AreaClienteAvisosRoute
  AreaClienteConexaoRoute: typeof AreaClienteConexaoRoute
  AreaClienteFinanceiroRoute: typeof AreaClienteFinanceiroRoute
  AreaClienteWifiRoute: typeof AreaClienteWifiRoute
  AreaClienteIndexRoute: typeof AreaClienteIndexRoute
}

const AreaRouteChildren: AreaRouteChildren = {
  AreaClienteAtendimentoRoute: AreaClienteAtendimentoRoute,
  AreaClienteAvisosRoute: AreaClienteAvisosRoute,
  AreaClienteConexaoRoute: AreaClienteConexaoRoute,
  AreaClienteFinanceiroRoute: AreaClienteFinanceiroRoute,
  AreaClienteWifiRoute: AreaClienteWifiRoute,
  AreaClienteIndexRoute: AreaClienteIndexRoute,
}

const AreaRouteWithChildren = AreaRoute._addFileChildren(AreaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AreaRoute: AreaRouteWithChildren,
  AuthRoute: AuthRoute,
  ClienteLoginRoute: ClienteLoginRoute,
  ApiPublicClienteAvisosRoute: ApiPublicClienteAvisosRoute,
  ApiPublicClienteFinanceiroRoute: ApiPublicClienteFinanceiroRoute,
  ApiPublicClienteMeRoute: ApiPublicClienteMeRoute,
  ApiPublicClienteNotificacoesRoute: ApiPublicClienteNotificacoesRoute,
  ApiPublicMikrotikStatusRoute: ApiPublicMikrotikStatusRoute,
  ApiPublicMikrotikSyncRoute: ApiPublicMikrotikSyncRoute,
  ApiPublicClienteAuthLoginRoute: ApiPublicClienteAuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
